import React,{useEffect,useMemo,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import Fuse from "fuse.js";
import type {Changes,Graph,Kind,Node} from "./types";
import "./style.css";
const modes=["graph","tree","metro","dictionary"] as const; type Mode=typeof modes[number];
const label:Record<Kind,string>={genre:"Genre",scene_movement:"Scene / Movement",descriptor:"Descriptor",meta:"Category"};
const typeClass:Record<Kind,string>={genre:"dot",scene_movement:"diamond",descriptor:"pill",meta:"square"};
function param(){const p=new URLSearchParams(location.search);return {mode:(modes.includes(p.get("mode") as Mode)?p.get("mode"):"graph") as Mode,id:p.get("genre")||""}}
function App(){const initial=param(); const [graph,setGraph]=useState<Graph>();const [changes,setChanges]=useState<Changes>();const [mode,setMode]=useState<Mode>(initial.mode);const [selected,setSelected]=useState(initial.id);const [query,setQuery]=useState("");const [open,setOpen]=useState(false);const [filters,setFilters]=useState<Record<Kind,boolean>>({genre:true,scene_movement:true,descriptor:true,meta:false});const [onlyMulti,setOnlyMulti]=useState(false); const input=useRef<HTMLInputElement>(null);
useEffect(()=>{Promise.all([fetch("./data/graph.json").then(r=>r.ok?r.json():Promise.reject()),fetch("./data/changes.json").then(r=>r.ok?r.json():null)]).then(([g,c])=>{setGraph(g);setChanges(c)}).catch(()=>setGraph({nodes:[],edges:[]}));},[]);
useEffect(()=>{const go=(e:KeyboardEvent)=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();input.current?.focus()}if(e.key==="Escape"){setOpen(false);setSelected("")}};addEventListener("keydown",go);return()=>removeEventListener("keydown",go)},[]);
const nodes=useMemo(()=>graph?.nodes.filter(n=>filters[n.type]&&(!onlyMulti||n.parents.length>1))||[],[graph,filters,onlyMulti]);
const fuse=useMemo(()=>new Fuse(nodes,{keys:["name","aliases"],threshold:.35}),[nodes]); const results=query?fuse.search(query).slice(0,9).map(x=>x.item):[]; const current=graph?.nodes.find(n=>n.id===selected);
function choose(id:string,next?:Mode){setSelected(id);setQuery("");setOpen(false);if(next)setMode(next);const p=new URLSearchParams({genre:id,mode:next||mode});history.pushState({},"",`?${p}`)}
function changeMode(next:Mode){setMode(next); const p=new URLSearchParams({mode:next});if(selected)p.set("genre",selected);history.pushState({},"",`?${p}`)}
if(!graph)return <main className="loading"><b>RYM Atlas</b><span>Loading taxonomy…</span></main>;
if(!graph.nodes.length)return <main className="loading"><b>RYM Atlas</b><span>RYM Atlas could not load the taxonomy dataset.</span><button onClick={()=>location.reload()}>Retry</button></main>;
return <div className="app"><header><div className="brand"><b>RYM Atlas</b><small>Taxonomy explorer</small></div><nav aria-label="Browsing mode">{modes.map(m=><button className={mode===m?"active":""} onClick={()=>changeMode(m)} key={m}>{m.toUpperCase()}</button>)}</nav><div className="search"><input ref={input} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} placeholder="Search taxonomy  /" aria-label="Search taxonomy"/>{open&&results.length>0&&<div className="results">{results.map(n=><button key={n.id} onClick={()=>choose(n.id)}><i className={typeClass[n.type]}/><span>{n.name}<small>{label[n.type]} · {n.parents.map(p=>graph.nodes.find(x=>x.id===p)?.name).filter(Boolean).join(" → ")}</small></span></button>)}</div>}</div><button className="filter" onClick={()=>setOnlyMulti(!onlyMulti)} aria-pressed={onlyMulti}>FILTER {onlyMulti?"MULTI":"ALL"}</button><button onClick={()=>changeMode("dictionary")}>A–Z</button></header><div className="workspace"><aside className="rail"><strong>TYPE FILTERS</strong>{(Object.keys(filters) as Kind[]).map(k=><label key={k}><input type="checkbox" checked={filters[k]} onChange={()=>setFilters({...filters,[k]:!filters[k]})}/>{label[k]}</label>)}<label><input type="checkbox" checked={onlyMulti} onChange={()=>setOnlyMulti(!onlyMulti)}/>Multiple parents</label><hr/><button onClick={()=>setMode("dictionary")}>Dictionary index</button><button onClick={()=>setMode("graph")}>Reset map</button></aside><section className="canvas">{mode==="graph"&&<GraphView nodes={nodes} selected={selected} onSelect={choose}/>} {mode==="tree"&&<TreeView graph={graph} nodes={nodes} selected={selected} onSelect={choose}/>} {mode==="metro"&&<MetroView graph={graph} nodes={nodes} selected={selected} onSelect={choose}/>} {mode==="dictionary"&&<Dictionary nodes={nodes} graph={graph} selected={selected} onSelect={choose}/>} </section>{current&&<Inspector node={current} graph={graph} changes={changes} onMode={changeMode} onClose={()=>setSelected("")}/>}</div></div>}
function GraphView({nodes,selected,onSelect}:{nodes:Node[];selected:string;onSelect:(id:string)=>void}){const visible=nodes.filter(n=>n.depth===null||n.depth<4).slice(0,180); const lookup=new Map(nodes.map(n=>[n.id,n]));return <div className="graph"><div className="graphhint">Scroll to zoom · drag to pan · select a node to inspect relationships</div><svg viewBox="0 0 1000 680" role="img" aria-label="Taxonomy relationship graph">{visible.flatMap((n,i)=>n.parents.filter(p=>lookup.has(p)).map((p,j)=>{const a=visible.indexOf(lookup.get(p)!);return <line key={p+n.id} x1={80+(a%9)*110} y1={90+Math.floor(a/9)*90} x2={80+(i%9)*110} y2={90+Math.floor(i/9)*90}/>}))}{visible.map((n,i)=><g key={n.id} tabIndex={0} onClick={()=>onSelect(n.id)} className={selected===n.id?"selected":""}><circle cx={80+(i%9)*110} cy={90+Math.floor(i/9)*90} r={n.type==="scene_movement"?12:9}/><text x={94+(i%9)*110} y={94+Math.floor(i/9)*90}>{n.name}</text></g>)}</svg></div>}
function TreeView({graph,nodes,selected,onSelect}:{graph:Graph;nodes:Node[];selected:string;onSelect:(id:string)=>void}){const [expanded,setExpanded]=useState(new Set(nodes.filter(n=>n.parents.length===0).map(n=>n.id)));const lookup=new Map(nodes.map(n=>[n.id,n]));function row(n:Node,depth:number):React.ReactNode{const children=n.children.map(x=>lookup.get(x)).filter(Boolean) as Node[];return <div key={n.id}><button className={selected===n.id?"tree selected":"tree"} style={{paddingLeft:16+depth*20}} onClick={()=>onSelect(n.id)}>{children.length? <span onClick={e=>{e.stopPropagation();const z=new Set(expanded);z.has(n.id)?z.delete(n.id):z.add(n.id);setExpanded(z)}}>{expanded.has(n.id)?"−":"+"}</span>:"·"}<i className={typeClass[n.type]}/>{n.name}{n.parents.length>1&&<em>↗ {n.parents.length} parents</em>}</button>{expanded.has(n.id)&&children.map(c=>row(c,depth+1))}</div>}return <div className="treeview"><h2>Hierarchy</h2>{nodes.filter(n=>n.parents.length===0).map(n=>row(n,0))}</div>}
function MetroView({graph,nodes,selected,onSelect}:{graph:Graph;nodes:Node[];selected:string;onSelect:(id:string)=>void}){const roots=nodes.filter(n=>n.parents.length===0).slice(0,12);return <div className="metro"><h2>Taxonomy Lines</h2><p>Major root families are transit lines. Interchange stations have multiple parents.</p>{roots.map((r,i)=>{const line=[r,...r.children.map(id=>nodes.find(n=>n.id===id)).filter(Boolean) as Node[]].slice(0,8);return <div className="line" style={{"--line":`hsl(${i*37} 68% 58%)`} as React.CSSProperties} key={r.id}>{line.map(n=><button className={selected===n.id?"station active":"station"} onClick={()=>onSelect(n.id)} key={n.id}><i/>{n.name}{n.parents.length>1&&" ⊙"}</button>)}</div>})}</div>}
function Dictionary({nodes,graph,selected,onSelect}:{nodes:Node[];graph:Graph;selected:string;onSelect:(id:string)=>void}){const [compact,setCompact]=useState(true);const groups=useMemo(()=>{const out:Record<string,Node[]>={};[...nodes].sort((a,b)=>a.name.localeCompare(b.name)).forEach(n=>{const k=/[A-Z]/i.test(n.name[0])?n.name[0].toUpperCase():"#";(out[k]??=[]).push(n)});return out},[nodes]);return <div className="dictionary"><div className="az">{"#ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(k=><a href={`#letter-${k}`} key={k}>{k}</a>)}<button onClick={()=>setCompact(!compact)}>{compact?"EXPAND":"COMPACT"}</button></div>{Object.entries(groups).map(([k,items])=><section id={`letter-${k}`} key={k}><h2>{k}</h2>{items.map(n=><article className={selected===n.id?"entry selected":"entry"} key={n.id} onClick={()=>onSelect(n.id)}><i className={typeClass[n.type]}/><div><b>{n.name}</b><small>{label[n.type]} · {n.parents.length} parents · {n.children.length} children</small>{!compact&&<p>Parents: {n.parents.map(id=>graph.nodes.find(x=>x.id===id)?.name).filter(Boolean).join(", ")||"Root category"}</p>}</div><button onClick={e=>{e.stopPropagation();onSelect(n.id)}}>View</button></article>)}</section>)}</div>}
function Inspector({node,graph,changes,onMode,onClose}:{node:Node;graph:Graph;changes?:Changes;onMode:(m:Mode)=>void;onClose:()=>void}){const name=(ids:string[])=>ids.map(i=>graph.nodes.find(n=>n.id===i)?.name).filter(Boolean).join(", ");const isNew=changes?.addedNodes.includes(node.id);return <aside className="inspector"><button className="close" onClick={onClose}>×</button><i className={typeClass[node.type]}/><h2>{node.name}</h2><p>{label[node.type]} {isNew&&<mark>NEW</mark>}</p><dl><dt>Parents</dt><dd>{name(node.parents)||"Root category"}</dd><dt>Children</dt><dd>{name(node.children)||"None"}</dd><dt>Depth</dt><dd>{node.depth??"—"}</dd></dl><div className="actions">{modes.map(m=><button key={m} onClick={()=>onMode(m)}>Show in {m}</button>)}</div>{node.rymUrl&&<a href={node.rymUrl} target="_blank" rel="noreferrer">Open on RYM</a>}<button onClick={()=>navigator.clipboard.writeText(location.href)}>Copy link</button></aside>}
createRoot(document.getElementById("root")!).render(<App/>);