import React,{useEffect,useMemo,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import Fuse from "fuse.js";
import type {Graph,Kind,Node} from "./types";
import "./style.css";
type Mode="graph"|"tree"|"dictionary"; type Source="rym"|"discogs";
const modes:Mode[]=["graph","tree","dictionary"];
const typeName:Record<Kind,string>={genre:"장르",scene_movement:"신 / 무브먼트",descriptor:"",meta:"카테고리"};
const marker:Record<Kind,string>={genre:"•",scene_movement:"◦",descriptor:"",meta:"▪"};
const visible=(n:Node)=>n.type!=="descriptor";
function pageState(){const q=new URLSearchParams(location.search);const raw=q.get("mode");return {mode:modes.includes(raw as Mode)?raw as Mode:"graph",genre:q.get("genre")||""}}
function nodeElement(id:string){return [...document.querySelectorAll<HTMLElement>("[data-node-id]")].find(e=>e.dataset.nodeId===id)}
function App(){const initial=pageState();const [graph,setGraph]=useState<Graph>();const [mode,setMode]=useState<Mode>(initial.mode);const [source,setSource]=useState<Source>("rym");const [selected,setSelected]=useState(initial.genre);const [query,setQuery]=useState("");const [searchOpen,setSearchOpen]=useState(false);const input=useRef<HTMLInputElement>(null);
useEffect(()=>{fetch("./data/graph.json").then(r=>r.ok?r.json():Promise.reject()).then(setGraph).catch(()=>setGraph({nodes:[],edges:[]}))},[]);
useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();input.current?.focus()}if(e.key==="Escape"){setSearchOpen(false);setSelected("")}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
const nodes=useMemo(()=>graph?.nodes.filter(visible)||[],[graph]);const fuse=useMemo(()=>new Fuse(nodes,{keys:["name","aliases"],threshold:.34}),[nodes]);const results=query?fuse.search(query).slice(0,10).map(r=>r.item):[];const current=nodes.find(n=>n.id===selected);
function select(id:string,next?:Mode){const target=next||mode;setSelected(id);setQuery("");setSearchOpen(false);if(next)setMode(next);const q=new URLSearchParams({mode:target,genre:id});history.pushState({},"",`?${q}`);setTimeout(()=>nodeElement(id)?.scrollIntoView({behavior:"smooth",block:"center"}),60)}
function changeMode(next:Mode){setMode(next);const q=new URLSearchParams({mode:next});if(selected)q.set("genre",selected);history.pushState({},"",`?${q}`);if(selected)setTimeout(()=>nodeElement(selected)?.scrollIntoView({behavior:"smooth",block:"center"}),60)}
if(!graph)return <main className="message"><b>GenreDict</b><span>장르 데이터를 불러오는 중...</span></main>;
if(!graph.nodes.length)return <main className="message"><b>GenreDict</b><span>장르 데이터를 불러오지 못했습니다.</span><button onClick={()=>location.reload()}>다시 시도</button></main>;
return <div className="app"><header className="header"><div className="title">GenreDict</div><SourceTabs source={source} onChange={setSource}/><nav aria-label="탐색 방식">{([['graph','맵'],['tree','트리'],['dictionary','사전']] as const).map(([key,name])=><button key={key} className={mode===key?"active":""} onClick={()=>changeMode(key)}>{name}</button>)}</nav><div className="search"><input ref={input} value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} placeholder="장르 검색..." aria-label="장르 검색"/>{searchOpen&&results.length>0&&<div className="results">{results.map(n=><button key={n.id} onClick={()=>select(n.id)}><b>{n.name}</b><small>{typeName[n.type]}{n.parents.length?` · ${n.parents.map(p=>nodes.find(x=>x.id===p)?.name).filter(Boolean).slice(0,2).join(", ")}`:""}</small></button>)}</div>}</div></header>{source==="discogs"?<main className="coming">Discogs 장르는 준비 중입니다.</main>:<main className="content">{mode==="graph"&&<GenreMap nodes={nodes} selected={selected} onSelect={select}/>} {mode==="tree"&&<TreeView nodes={nodes} selected={selected} onSelect={select}/>} {mode==="dictionary"&&<Dictionary nodes={nodes} selected={selected} onSelect={select}/>} {current&&<Inspector node={current} nodes={nodes} mode={mode} onSelect={select} onMode={changeMode} onClose={()=>setSelected("")}/>}</main>}</div>}
function SourceTabs({source,onChange}:{source:Source;onChange:(s:Source)=>void}){return <div className="source-tabs" aria-label="데이터 소스"><button className={source==="rym"?"active":""} onClick={()=>onChange("rym")}>RYM 장르</button><button className={source==="discogs"?"active":""} onClick={()=>onChange("discogs")}>Discogs 장르</button></div>}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0)/4294967295}
function useWidth(){const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(900);useEffect(()=>{const el=ref.current;if(!el)return;const update=()=>setWidth(Math.max(280,el.clientWidth));update();const obs=new ResizeObserver(update);obs.observe(el);return()=>obs.disconnect()},[]);return [ref,width] as const}
function mapLayout(nodes:Node[],width:number){const allowed=new Map(nodes.map(n=>[n.id,n]));const children=(n:Node)=>n.children.map(id=>allowed.get(id)).filter(Boolean) as Node[];const roots=nodes.filter(n=>!n.parents.some(p=>allowed.has(p))).sort((a,b)=>a.name.localeCompare(b.name));const ordered:Node[]=[];const seen=new Set<string>();const visit=(n:Node)=>{if(seen.has(n.id))return;seen.add(n.id);ordered.push(n);children(n).sort((a,b)=>a.name.localeCompare(b.name)).forEach(visit)};roots.forEach(visit);nodes.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(visit);const placed=new Map<string,{x:number;y:number}>();const side=12;ordered.forEach((n,i)=>{const nameWidth=Math.min(220,Math.max(45,n.name.length*6.3));const parents=n.parents.map(p=>placed.get(p)).filter(Boolean) as {x:number;y:number}[];const seed=hash(n.id);const preferred=parents.length?parents.reduce((sum,p)=>sum+p.x,0)/parents.length:side+(width-nameWidth-side*2)*seed;const drift=(seed-.5)*width*.28;const x=Math.max(side,Math.min(width-nameWidth-side,preferred+drift));placed.set(n.id,{x,y:32+i*27+(hash(n.id+"y")-.5)*5})});return {ordered,placed,height:ordered.length*27+80}}
function GenreMap({nodes,selected,onSelect}:{nodes:Node[];selected:string;onSelect:(id:string)=>void}){const [ref,width]=useWidth();const {ordered,placed,height}=useMemo(()=>mapLayout(nodes,width),[nodes,width]);const connected=useMemo(()=>{const set=new Set<string>();const n=nodes.find(n=>n.id===selected);if(n){set.add(n.id);n.parents.forEach(x=>set.add(x));n.children.forEach(x=>set.add(x))}return set},[nodes,selected]);return <section className="map" ref={ref} style={{minHeight:height}} aria-label="장르 지도"><svg className="edges" viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" aria-hidden="true">{ordered.flatMap(n=>n.parents.map(p=>{const a=placed.get(p),b=placed.get(n.id);return a&&b?<line className={selected&&(n.id===selected||p===selected)?"related":""} key={`${p}-${n.id}`} x1={a.x+12} y1={a.y} x2={b.x+12} y2={b.y}/>:null}))}</svg>{ordered.map(n=>{const p=placed.get(n.id)!;return <button key={n.id} data-node-id={n.id} className={`map-node ${n.type} ${selected===n.id?"selected":""} ${connected.has(n.id)?"connected":""}`} style={{left:p.x,top:p.y}} onClick={()=>onSelect(n.id)}><span>{marker[n.type]}</span>{n.name}</button>})}</section>}
function TreeView({nodes,selected,onSelect}:{nodes:Node[];selected:string;onSelect:(id:string)=>void}){const lookup=new Map(nodes.map(n=>[n.id,n]));const [expanded,setExpanded]=useState(()=>new Set(nodes.map(n=>n.id)));const roots=nodes.filter(n=>!n.parents.some(p=>lookup.has(p)));function render(n:Node,depth:number):React.ReactNode{const kids=n.children.map(id=>lookup.get(id)).filter(Boolean) as Node[];return <div key={n.id}><button data-node-id={n.id} className={`tree-node ${selected===n.id?"selected":""}`} style={{paddingLeft:12+depth*17}} onClick={()=>onSelect(n.id)}>{kids.length>0&&<span onClick={e=>{e.stopPropagation();const next=new Set(expanded);next.has(n.id)?next.delete(n.id):next.add(n.id);setExpanded(next)}}>{expanded.has(n.id)?"−":"+"}</span>}<i>{marker[n.type]}</i>{n.name}{n.parents.length>1&&<small>상위 장르 {n.parents.length}개</small>}</button>{expanded.has(n.id)&&kids.sort((a,b)=>a.name.localeCompare(b.name)).map(k=>render(k,depth+1))}</div>}return <section className="tree-view"><h1>장르 계보</h1>{roots.sort((a,b)=>a.name.localeCompare(b.name)).map(n=>render(n,0))}</section>}
function Dictionary({nodes,selected,onSelect}:{nodes:Node[];selected:string;onSelect:(id:string)=>void}){const groups=useMemo(()=>{const g:Record<string,Node[]>={};nodes.slice().sort((a,b)=>a.name.localeCompare(b.name)).forEach(n=>{const k=/[A-Za-z]/.test(n.name[0])?n.name[0].toUpperCase():"#";(g[k]??=[]).push(n)});return g},[nodes]);return <section className="dictionary"><div className="az">{"#ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(letter=><a key={letter} href={`#letter-${letter}`}>{letter}</a>)}</div>{Object.entries(groups).map(([letter,items])=><section id={`letter-${letter}`} key={letter}><h1>{letter}</h1>{items.map(n=><button data-node-id={n.id} className={`entry ${selected===n.id?"selected":""}`} onClick={()=>onSelect(n.id)} key={n.id}><b><i>{marker[n.type]}</i>{n.name}</b><small>{typeName[n.type]} · 상위 {n.parents.length} · 하위 {n.children.length}</small></button>)}</section>)}</section>}
function Inspector({node,nodes,mode,onSelect,onMode,onClose}:{node:Node;nodes:Node[];mode:Mode;onSelect:(id:string,next?:Mode)=>void;onMode:(m:Mode)=>void;onClose:()=>void}){const lookup=new Map(nodes.map(n=>[n.id,n]));const [copied,setCopied]=useState(false);const list=(ids:string[],empty:string)=>ids.length?<ul>{ids.map(id=>{const n=lookup.get(id);return n?<li key={id}><button onClick={()=>onSelect(id,"graph")}>{n.name}</button></li>:null})}</ul>:<p>{empty}</p>;return <aside className="inspector"><button className="close" onClick={onClose} aria-label="닫기">×</button><h1>{node.name}</h1><p className="kind">{typeName[node.type]}</p><h2>상위 장르</h2>{list(node.parents,"상위 장르가 없습니다.")}<h2>하위 장르</h2>{list(node.children,"하위 장르가 없습니다.")}<h2>깊이</h2><p>{node.depth??"—"}</p><div className="panel-nav">{mode!=="graph"&&<button onClick={()=>onMode("graph")}>맵에서 보기</button>}{mode!=="tree"&&<button onClick={()=>onMode("tree")}>트리에서 보기</button>}{mode!=="dictionary"&&<button onClick={()=>onMode("dictionary")}>사전에서 보기</button>}</div>{node.rymUrl&&<a href={node.rymUrl} target="_blank" rel="noreferrer">RYM에서 보기 ↗</a>}<button className="copy" onClick={()=>{navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1200)}}>{copied?"복사됨":"링크 복사"}</button></aside>}
createRoot(document.getElementById("root")!).render(<App/>);